services:
  pubmed-miner:
    build: .
    container_name: pubmed-miner
    ports:
      - "8501:8501"
    environment:
      # Add your API keys here or use .env file
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NCBI_API_KEY=${NCBI_API_KEY}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      # Rate limiting
      - GEMINI_RPM=${GEMINI_RPM:-10}
      - GEMINI_TPM=${GEMINI_TPM:-180000}
      - PAPER_PAUSE_SEC=${PAPER_PAUSE_SEC:-3.0}
    volumes:
      # Mount .env file if it exists
      - ./.env:/app/.env:ro
      # Optional: Mount data directory for persistence
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add a reverse proxy for production
# nginx:
#   image: nginx:alpine
#   container_name: pubmed-miner-nginx
#   ports:
#     - "80:80"
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf:ro
#   depends_on:
#     - pubmed-miner
#   restart: unless-stopped
